<template>
  <div>
    <div class="loadingio-spinner-rolling-qopubdazyn">
      <div class="ldio-zrnhjo5u8gj">
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Loading',
};
</script>

<style scoped>
@keyframes ldio-zrnhjo5u8gj {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-zrnhjo5u8gj div {
  position: absolute;
  width: 76px;
  height: 76px;
  border: 20px solid #1d3f72;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-zrnhjo5u8gj div {
  animation: ldio-zrnhjo5u8gj 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-qopubdazyn {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-zrnhjo5u8gj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-zrnhjo5u8gj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>